Send `branch` when skipping
chromaui/chromatic-cli pull request #474
Opened 2021-12-10 04:31 UTC by tmeasday

For https://github.com/chromaui/chromatic-cli/issues/351.

Relies on https://github.com/chromaui/chromatic/pull/5707

2021-12-13 05:01 UTC, tmeasday commented
The branch has now been merged + released, can we release this change?

2021-12-13 18:42 UTC, ghengeveld requested changes

2021-12-13 18:42 UTC, ghengeveld commented on bin-src/tasks/gitInfo.js
> +    if (await ctx.client.runQuery(TesterSkipBuildMutation, { commit, branch })) {
We should also send `slug`.

2021-12-21 13:41 UTC, ghengeveld requested changes

2021-12-21 13:41 UTC, ghengeveld commented on bin-src/tasks/gitInfo.js
> +    skipBuild(commit: $commit, branch: $branch)
I think you intended to send $slug as well?

2022-01-13 05:36 UTC, tmeasday commented
@ghengeveld what is the best way to test this? I pushed the upstream branch https://github.com/chromaui/chromatic/pull/5732 to staging

2022-01-13 08:23 UTC, ghengeveld commented
> @ghengeveld what is the best way to test this? I pushed the upstream branch [chromaui/chromatic#5732](https://github.com/chromaui/chromatic/pull/5732) to staging

You'll need a PR from a fork and then trigger a skipBuild with that `ownerName:branchName` combo. The `--branch-name` flag supports that format (it will override the detected slug if you do). Then I guess you can check Loggly for `Succesfully synced commit status for UI Review` with `Skipped build.` as the description.

2022-01-14 03:41 UTC, tmeasday commented
> You'll need a PR from a fork and then trigger a skipBuild with that ownerName:branchName combo. The --branch-name flag supports that format (it will override the detected slug if you do). Then I guess you can check Loggly for Succesfully synced commit status for UI Review with Skipped build. as the description.

Thanks, that's useful, but actually what I just meant is how can I test this branch of the CLI?

2022-01-17 01:07 UTC, tmeasday commented
Awesome. Worked! Thanks @ghengeveld 

![image](https://user-images.githubusercontent.com/132554/149686003-f4e9ad37-4dff-4316-88eb-2274fe908d84.png)

https://github.com/chromaui/shapes/pull/44

2022-01-17 15:52 UTC, ghengeveld approved these changes

2022-01-17 23:59 UTC, tmeasday commented
I'll let you merge + release this @ghengeveld ?

2022-01-18 09:24 UTC, merged